### ISSUE TITLE
Support "Don't ask again"

### ISSUE THREAD

**Issue by petersalomonsen** [NEARBuilders/bos-workspace#114]
The "Don't ask again" feature does not work with the BOS-workspace gateway.

<img width="848" alt="image" src="https://github.com/NEARBuilders/bos-workspace/assets/9760441/d857a6b1-6ebb-4372-8c00-2474b0b7b1be">

As you can see it is only displaying "Don't ask again for sending similar transactions by", and that's all, but it should also show the widget name.

The reason for this is because of using the redirectmap, and the fix would be to make sure that the RPC proxy intercepts and replaces requests for widget source code with local content ( and stop using the redirectmap ). I know this will work, since I've already tested it in the DevHub playwright tests.

**Comment by elliotBraem** [comment]
Local gateway is hardcoded with proxy RPC requests (see [here](https://github.com/NEARBuilders/bos-workspace/blob/12c5c5980bf51413dc6003575e9b59906cf7138c/gateway/src/useAuth.js#L25))

But is also configured for redirect map [here](https://github.com/NEARBuilders/bos-workspace/blob/12c5c5980bf51413dc6003575e9b59906cf7138c/gateway/src/index.js#L47). This is only used for hot reload -- hot reload can be disabled via "bos-workspace dev --no-hot"

Try disabling hot reload and see if it works then

**Comment by petersalomonsen** [comment]
even with `--no-hot` I get this:


<img width="841" alt="image" src="https://github.com/NEARBuilders/bos-workspace/assets/9760441/cdde075b-833e-4b2a-b749-5d21f7ce91f2">

**Comment by elliotBraem** [comment]
This is resolved now with #115, --no-hot will not trigger redirectMap
