### ISSUE TITLE
Installing doesn't expose bos-workspace or bw 

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/bos-workspace#17]
This broke in latest alpha version: 

neither installing it globally or in the repository exposed bos-workspace or bw to be used.

We should make sure this works before transferring it over. 

Most projects using bos-workspace are set to this version atm:

```
   "bos-workspace": "github:nearbuilders/bos-workspace#main"
```

**Comment by TheLubab** [comment]
Fixed :) https://github.com/sekaiking/bos-workspace/releases/tag/0.0.1-alpha.2
