### ISSUE TITLE
Tried installing bos-cli-rs using rust package manager cargo . it got failed in the middle   Error configuring OpenSSL build:

### ISSUE THREAD

**Issue by Eren-Yeaager** [NEARBuilders/bos-workspace#34]
I am currently on my Windows machine. the exact error that occurred during the installation was 

error: failed to run custom build command for `openssl-sys v0.9.97`                                                       

Caused by:
  process didn't exit successfully: `C:\Users\SASWAT~1\AppData\Local\Temp\cargo-installW4uxhg\release\build\openssl-sys-a52d4764de55824a\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Users\\SASWAT~1\\AppData\\Local\\Temp\\cargo-installW4uxhg\\release\\build\\openssl-sys-8d11540cf2537ff2\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at C:\Users\saswat marpureddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-src-300.1.6+3.1.4\src\lib.rs:585:9:

  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=C:\\Users\\SASWAT~1\\AppData\\Local\\Temp\\cargo-installW4uxhg\\release\\build\\openssl-sys-8d11540cf2537ff2\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN64A"
      Failed to execute: program not found

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bos-cli v0.3.6 (https://github.com/FroVolod/bos-cli-rs#46037ed0)`, intermediate artifacts can be found at `C:\Users\SASWAT~1\AppData\Local\Temp\cargo-installW4uxhg`

**Comment by TheLubab** [comment]
If you wanna work with Rust in windows, it's better to use [WSL2](https://learn.microsoft.com/en-us/windows/wsl/install). Otherwise, just install pre-compiled binaries like this:
```
npm install -g bos-cli
```

**Comment by Eren-Yeaager** [comment]
@sekaiking I have used both of them but still its not working. any other work around available?

**Comment by TheLubab** [comment]
You can try installing OpenSSL https://wiki.openssl.org/index.php/Binaries. If it doesn't work still, ask here https://github.com/bos-cli-rs/bos-cli-rs they can help you better.
